### PR TITLE
Replace mod name spaces with dash

### PR DESCRIPTION
**Pull request by FlashyReese**
- Adds the missing space for the logger.
- ~~Replaces any whitespaces with a dash for our JSON key.~~

Todo:
- Sanitize any non-alphanumeric characters for mod name or just swap out for mod identifier.

### CODE REVIEW

**Comment by altrisi** [comment]
Oh I should probably also get log4j out of there...

Also, note that you can change the json key in the builder if you need to, having those changed by default may be unexpected given the docs don't mention it. Does floader not accept spaces in custom values?

**Comment by FlashyReese** [comment]
It does support spaces in custom values
```json
  "custom": {
    "sodium extra:options": {
      "mixin.fog": false
    }
  }
```
doesn't look too pleasant.
  
Edit: 
I somehow manage to miss the fact that you can change the JSON key in the builder. 

I will leave this open to remind you about Log4j.

**Comment by altrisi** [comment]
Also about no space in the logger name, it was on purpose given LithiumConfig and SodiumConfig don't have a space in the logger name (you can also replace the logger from the builder). But I'll change it anyway given I agree it looks better.

About log4j: Just noticed that you also publish your mod that uses this for 1.16 and 1.17, and slf4j was only added in 1.18.2. Will that cause problems, or just older versions would use an older lib version? If it causes, I could just not change it until the decision at CaffeineMC about what to do about the system are finished. Sodium next is also still on 1.18.1 so it wouldn't be compatible either (though I expect that not to be an issue, just that it hasn't been a priority yet).

Thanks for the PR though!

**Comment by altrisi** [comment]
Actually, isn't this built against Java 16? How do you make it work on 1.16.5?

**Comment by FlashyReese** [comment]
> Will that cause problems, or just older versions would use an older lib version?

It will likely cause issues.

> Actually, isn't this built against Java 16? How do you make it work on 1.16.5?

I have no idea, I assume it's because the code itself doesn't actually use any of Java 16 features. It's compiled with Java 16 but still runs fine on Java 8.

**Comment by altrisi** [comment]
Decided to change it. You should be able to keep using the old commit on 1.16.5, the rest of methods haven't change so it shouldn't be an issue. If there's later changes you need they can always be backported, though I don't plan on doing any additions to the lib.

Related: #3.

**Pull request closed without merging**
